"""add users and addresss tables

Revision ID: cb81e02d939f
Revises:
Create Date: 2020-05-05 09:36:50.457767

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = "cb81e02d939f"
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "users_address",
        sa.Column("id", postgresql.UUID(), nullable=False),
        sa.Column("city", sa.String(length=32), nullable=False),
        sa.Column("complement", sa.String(length=128), nullable=True),
        sa.Column("country", sa.String(length=64), nullable=False),
        sa.Column("number", sa.String(length=16), nullable=False),
        sa.Column("postal_code", sa.String(length=8), nullable=False),
        sa.Column("state", sa.String(length=2), nullable=False),
        sa.Column("street", sa.String(length=128), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "users_user",
        sa.Column("id", postgresql.UUID(), nullable=False),
        sa.Column("address_id", postgresql.UUID(), nullable=True),
        sa.Column("email", sa.String(length=255), nullable=False),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("name", sa.String(length=64), nullable=False),
        sa.Column("password", sa.String(length=248), nullable=False),
        sa.Column("permissions", postgresql.ARRAY(sa.String()), nullable=False),
        sa.ForeignKeyConstraint(["address_id"], ["users_address.id"]),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_users_user_email"), "users_user", ["email"], unique=False)
    op.create_index(op.f("ix_users_user_name"), "users_user", ["name"], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_users_user_name"), table_name="users_user")
    op.drop_index(op.f("ix_users_user_email"), table_name="users_user")
    op.drop_table("users_user")
    op.drop_table("users_address")
    # ### end Alembic commands ###
